version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "64000:27017"
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      MYSQL_DATABASE: keycloak
      MYSQL_SCHEMA: keycloak
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile.keycloak
      args:
        DB_USERNAME: keycloak
        DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    depends_on:
      - mysql

volumes:
  mongo:
  rabbitmq:
  mysql:
