version: '3.8'


services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "64000:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    env_file:
      - .env
    networks:
      - mynetwork


  backend:
    image: nwdpiter/backend:1.0
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - mynetwork


  upload:
    image: nwdpiter/upload:1.0
    ports:
      - "5174:8080"
    restart: always
    depends_on:
      - backend
      - mongo
    networks:
      - mynetwork


  admin:
    image: nwdpiter/admin:1.0
    ports:
      - "5173:8080"
    restart: always
    depends_on:
      - backend
      - mongo
    networks:
      - mynetwork


  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge


volumes:
  mongo-data:
    driver: local
