services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_URL: ${DB_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inbcm-backend.rule=Host(`inbcm-backend.vitordaniel.com`)"
      - "traefik.http.routers.inbcm-backend.entrypoints=websecure"
      - "traefik.http.services.tomcat.loadbalancer.server.port=3000"
      - "traefik.http.routers.inbcm-backend.tls.certresolver=myresolver"
    networks:
      - traefik
      - internal

  mongo:
    networks:
      - internal

networks:
  internal:
  traefik:
    external: true
