services:
  backend:
    build:
      context: .
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_URL: ${DB_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inbcm-backend.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`) || Host(`admin.${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.inbcm-backend.entrypoints=websecure"
      - "traefik.http.services.inbcm-backend.loadbalancer.server.port=3000"
      - "traefik.http.routers.inbcm-backend.tls.certresolver=myresolver"
    networks:
      - internal
      - traefik

  mongo:
    networks:
      - internal

networks:
  internal:
  traefik:
    external: true
