version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "64000:27017"
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

volumes:
  mongo:
