name: Publish Docker image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - development
    types: [closed]

jobs:
  push_to_registry:
    name: Push Docker image to Registry
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set Docker repository name for main branch
        if: github.ref == 'refs/heads/main'
        run: echo "DOCKER_REPOSITORY=inbcm-backend-main" >> $GITHUB_ENV

      - name: Set Docker repository name for development branch
        if: github.ref == 'refs/heads/development'
        run: echo "DOCKER_REPOSITORY=inbcm-backend" >> $GITHUB_ENV

      - name: Truncate commit SHA
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:${{ github.event_name }}-${{ env.SHORT_SHA }}
            ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:latest